### ISSUE TITLE
Query params break router

### ISSUE THREAD

**Issue by lyptt** [STRML/react-router-component#149]
It seems that passing any kind of query parameter to a route will break the router with the following call stack:

```
TypeError: Cannot read property 'ref' of null
    at RouteRenderingMixin.renderRouteHandler ($PROJECT_DIR/node_modules/react-router-component/lib/RouteRenderingMixin.js:15:48)
    at React.createClass.render ($PROJECT_DIR/node_modules/react-router-component/lib/Router.js:34:26)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at ReactPerf.measure.wrapper ($PROJECT_DIR/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentMixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at ReactPerf.measure.wrapper [as mountComponent] ($PROJECT_DIR/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren ($PROJECT_DIR/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup ($PROJECT_DIR/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactPerf.measure.wrapper [as mountComponent] ($PROJECT_DIR/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren ($PROJECT_DIR/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup ($PROJECT_DIR/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactPerf.measure.wrapper [as mountComponent] ($PROJECT_DIR/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent ($PROJECT_DIR/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at ReactPerf.measure.wrapper [as mountComponent] ($PROJECT_DIR/node_modules/react/lib/ReactPerf.js:70:21)
    at $PROJECT_DIR/node_modules/react/lib/ReactServerRendering.js:42:27
    at ReactServerRenderingTransaction.Mixin.perform ($PROJECT_DIR/node_modules/react/lib/Transaction.js:134:20)
    at Object.renderToString ($PROJECT_DIR/node_modules/react/lib/ReactServerRendering.js:39:24)
    at renderRoute ($PROJECT_DIR/routes/public/index.js:33:21)
```

I don't really have control over users adding query parameters to my public routes, so this is a pretty nasty issue. I've tried making the regex match the query string but this doesn't appear to help. For example with the regex `^/home(\?.*)` I'd expect it to match /home followed by an optional query string, however this doesn't appear to work with the router at all.

**Comment by STRML** [comment]
Thanks. I'm going to see what I can do about this, it is obviously bad.

**Comment by STRML** [comment]
Do you have a NotFound route defined?

**Comment by STRML** [comment]
Querystrings are now passed as the prop `_query` to the handler. This is in v0.26.0.

**Comment by lyptt** [comment]
Sorry for the late reply, thanks for fixing this up so quickly!

**Comment by caasi** [comment]
How can I match both `/product/(:id)` and `/product/(:id)/` after [this change](https://github.com/STRML/react-router-component/blob/a6ca783f2c3c74d3cc5c7d7e5f236670ab380329/lib/matchRoutes.js#L27)?

**Comment by STRML** [comment]
I'm not sure how this change affects that use case. See the [url-pattern docs](https://github.com/snd/url-pattern). The pattern should be something like `/product/(:id)(/)`.

**Comment by caasi** [comment]
I used something like `/product/(:id)/?` before. Thank you for the tips.
